name: Bug report
description: Signaler un bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Décrire le bug observé
    validations:
      required: true
